# -*- coding: utf-8 -*-
"""확률적 경사 하강법.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1uyCxyhX3Uw3_Xz3-Q4gx19Ba9dG5NQyL
"""

# 작성 시작 날짜: 2021.09.16.목
# 프로그램 개요: 확률적 경사 하강법 - 생선의 특성들을 이용하여 생선 종류 예측하여 확률로 출력

