# -*- coding: utf-8 -*-
"""훈련세트와 테스트세트.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/13qoY529Z2a4e2445z5_3JSsh_c3TpHnS
"""

# 작성 날짜: 2021.08.19(목)
# 프로그램 개요: 훈련세트와 데이터 세트 나누기

#데이터 준비
fish_length = [25.4, 26.3, 26.5, 29.0, 29.0, 29.7, 29.7, 30.0, 30.0, 30.7, 31.0, 31.0, 
                31.5, 32.0, 32.0, 32.0, 33.0, 33.0, 33.5, 33.5, 34.0, 34.0, 34.5, 35.0, 
                35.0, 35.0, 35.0, 36.0, 36.0, 37.0, 38.5, 38.5, 39.5, 41.0, 41.0, 9.8, 
                10.5, 10.6, 11.0, 11.2, 11.3, 11.8, 11.8, 12.0, 12.2, 12.4, 13.0, 14.3, 15.0]
fish_weight = [242.0, 290.0, 340.0, 363.0, 430.0, 450.0, 500.0, 390.0, 450.0, 500.0, 475.0, 500.0, 
                500.0, 340.0, 600.0, 600.0, 700.0, 700.0, 610.0, 650.0, 575.0, 685.0, 620.0, 680.0, 
                700.0, 725.0, 720.0, 714.0, 850.0, 1000.0, 920.0, 955.0, 925.0, 975.0, 950.0, 6.7, 
                7.5, 7.0, 9.7, 9.8, 8.7, 10.0, 9.9, 9.8, 12.2, 13.4, 12.2, 19.7, 19.9]

#데이터와 타겟을 만듦
fish_data = [[l,w] for l,w in zip(fish_length, fish_weight)]
fish_target = [1]*35 + [0]*14

from sklearn.neighbors import KNeighborsClassifier
kn = KNeighborsClassifier()

#넘파이로 훈련세트와 테스트 세트 만들기

import numpy as np

input_arr = np.array(fish_data)
target_arr = np.array(fish_target)
print(input_arr, input_arr.shape)

index = np.arange(49)
np.random.shuffle(index)

print(index)
print(input_arr[index[1:3]])

train_input = input_arr[index[:35]]
train_target = target_arr[index[:35]]
test_input = input_arr[index[35:]]
test_target = target_arr[index[35:]]

print(train_input)
print(train_target)
print(test_input)
print(test_target)

print(test_input[:,0])

#matplotlib을 이용하여 train set와 tet set가 잘 섞였는지 확인

import matplotlib.pyplot as plt
plt.scatter(train_input[:,0], train_input[:,1])
plt.scatter(test_input[:,0], test_input[:,1])
plt.xlabel('length')
plt.ylabel('weight')
plt.show()

#훈련 & 테스트

kn = kn.fit(train_input, train_target)
kn.score(test_input, test_target)
kn.predict([[53,100]])